/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Esfera.glb -T 
Files: Esfera.glb [449.92KB] > C:\Users\jguerra\WebstormProjects\macbook_gsap_app\public\models\Esfera-transformed.glb [15.91KB] (96%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Esfera(props) {
  const { nodes, materials } = useGLTF('/models/Esfera-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Node1.geometry} material={materials.x1} />
    </group>
  )
}

useGLTF.preload('/models/Esfera-transformed.glb')
